On Error Resume Next

Set objArgs = WScript.Arguments

WorkbookPathRexmex = objArgs(0)
WorkbookSheetRexmex = objArgs(1)

'WorkbookPathRexmex = "C:\Users\HE678HU\OneDrive - EY\.Repsol\Reporte Regulatorio\4 - Abril\Files\REXMEX - Cuenta Operativa 2025_120525.xlsx"
'WorkbookSheetRexmex = "Cuenta Operativa"

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

'Abre libro Excel
Set WorkbookPathRexmex = objExcel.Workbooks.Open(WorkbookPathRexmex)
Set WorkbookSheetRexmex = WorkbookPathRexmex.Worksheets(WorkbookSheetRexmex)

' Verificar si los filtros están activos en la fila 1, si no, activarlos
If WorkbookSheetRexmex.AutoFilterMode Then
    WorkbookSheetRexmex.AutoFilterMode = False
End If

' Encontrar la última fila con datos en la columna a filtrar
lastRow = WorkbookSheetRexmex.Cells(WorkbookSheetRexmex.Rows.Count, 1).End(-4162).Row ' -4162 = xlUp

' Filtrar la columna 27 (AA) por valores diferentes de vacío
WorkbookSheetRexmex.Range(WorkbookSheetRexmex.Cells(1, 27), WorkbookSheetRexmex.Cells(lastRow, 27)).AutoFilter 27, "<>"

' Filtrar la columna 61 (BI) por celdas vacías
WorkbookSheetRexmex.Range(WorkbookSheetRexmex.Cells(1, 61), WorkbookSheetRexmex.Cells(lastRow, 61)).AutoFilter 61, "="

' Guardar y cerrar los libros de trabajo
WorkbookPathRexmex.Save
WorkbookPathRexmex.Close

' Cerrar la aplicación de Excel
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.Echo Msg
End if