On Error Resume Next

Set objArgs = WScript.Arguments

txtPath = objArgs(0)
xlsxPath = objArgs(1)

'txtPath = "C:\Users\HE678HU\Downloads\VistaFactura.txt"      ' Cambia la ruta al archivo TXT
'xlsxPath = "C:\Users\HE678HU\Downloads\VistaFactura.xlsx"   ' Cambia la ruta de salida XLSX

' Script para importar un archivo TXT separado por tabulaciones y guardarlo como XLSX

Dim objExcel, objWorkbook

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = True
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = True
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

' Abrir el archivo TXT como libro nuevo (OpenText)
' Parámetros: Filename, Origin, StartRow, DataType, TextQualifier, Tab, Semicolon, Comma, Space, Other, OtherChar
objExcel.Workbooks.OpenText txtPath, 437, 1, 1, 1, False, True, False, False, False, False

Set objWorkbook = objExcel.Workbooks(1)

' Guardar como XLSX
objWorkbook.SaveAs xlsxPath, 51 ' 51 = xlOpenXMLWorkbook (xlsx)


Set objWorksheet = objWorkbook.ActiveSheet

Const xlValues = -4163
Const xlPart = 2
	
Set mRange = objWorksheet.Range("H:H")
	
Dim mFind :	Set mFind = mRange.Find("Cta.mayor",,xlValues,xlPart)

If Not mFind Is Nothing Then
    ' Eliminar filas desde la fila 1 hasta mFind.Row
    objWorksheet.Rows("1:" & mFind.Row - 1).Delete
End If

' Obtener ultima columna con datos
Dim lastCol
lastCol = objWorksheet.Cells(1, objWorksheet.Columns.Count).End(-4159).Column ' -4159 = xlToLeft

Dim lastRowA

' Iterar desde la columna 1 hasta la última columna con datos lastCol
For i = lastCol To 1 Step -1
    lastRowA = objWorksheet.Cells(objWorksheet.Rows.Count, i).End(-4162).Row ' -4162 = xlUp
    ' Verificar si la celda de la primera fila está vacía
    If lastRowA = 1 Then
        objWorksheet.Columns(i).Delete
        'i = i + 1 ' Ajustar el índice después de eliminar la columna
    End If
Next

' Validar que la fila 2 no tenga datos
Dim isRow2Empty, colCount, j
isRow2Empty = True
colCount = objWorksheet.UsedRange.Columns.Count

' Obtener la última fila con datos en toda la hoja (no solo una columna)
Dim lastUsedRow
lastUsedRow = objWorksheet.UsedRange.Rows(objWorksheet.UsedRange.Rows.Count).Row

' Recorrer las filas desde la 1 hasta la última fila con datos
For i = lastUsedRow To 1 Step -1
    For j = 1 To colCount
        If Trim(objWorksheet.Cells(i, j).Value & "") <> "" Then
            isRow2Empty = False
            Exit For
        End If
    Next
    ' Si la fila está vacía, eliminarla
    If isRow2Empty Then
        objWorksheet.Rows(i).Delete
        i = i + 1 ' Ajustar el índice después de eliminar la fila
    End If
Next

objWorkbook.Save
objWorkbook.Close
'Quita la instancia del objeto Excel
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.Echo Msg
End if